# Generated by Django 5.0.1 on 2024-01-14 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedfile", name="id",),
        migrations.AddField(
            model_name="uploadedfile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
